### PR TITLE
chore: add support for DalamudPluginsD17

### PR DESCRIPTION
**Pull request by cecilia-sanare**
### Description

- Added support for [DIP17](https://github.com/goatcorp/DIPs/blob/main/text/17-automated-build-and-submit-pipeline.md)
- Fixed the pointer for Open Chat Bubble

### References

See https://github.com/goatcorp/DalamudPluginsD17

### Related PRs

#50

### CODE REVIEW

**Comment by MKhayle** [comment]
#50 has been merged, if you want to complete this draft.

**Comment by cecilia-sanare** [comment]
@MKhayle Alrighty! Just need to merge in the latest changes from `main` and validate something rq! c:

**Comment by cecilia-sanare** [comment]
@MKhayle Should be good to go!

**Comment by MKhayle** [comment]
Perfect, thanks !

**Pull request merged**
